"""empty message

Revision ID: 2ab4e759fa9e
Revises: 
Create Date: 2019-01-10 17:52:38.526000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ab4e759fa9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('route_path', sa.String(length=50), nullable=True))
    op.drop_column('article', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('path', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('article', 'route_path')
    # ### end Alembic commands ###
