"""empty message

Revision ID: 2d0c3c99ce38
Revises: 2ab4e759fa9e
Create Date: 2019-01-11 15:28:52.029000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d0c3c99ce38'
down_revision = '2ab4e759fa9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('column_name', sa.String(length=10), nullable=True))
    op.add_column('article', sa.Column('menu_id', sa.Integer(), nullable=False))
    op.add_column('article', sa.Column('menu_name', sa.String(length=10), nullable=True))
    op.alter_column('article', 'column_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('article', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('article', 'route_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('route_path', mysql.VARCHAR(length=50), nullable=True))
    op.alter_column('article', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('article', 'column_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('article', 'menu_name')
    op.drop_column('article', 'menu_id')
    op.drop_column('article', 'column_name')
    # ### end Alembic commands ###
