"""empty message

Revision ID: 38c231ae8462
Revises: 
Create Date: 2019-01-24 17:58:08.222000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c231ae8462'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenu', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('submenu', sa.Column('official_doc', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submenu', 'official_doc')
    op.drop_column('submenu', 'description')
    # ### end Alembic commands ###
