"""empty message

Revision ID: 39b9974eefef
Revises: 
Create Date: 2019-01-06 15:28:50.029666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39b9974eefef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'status',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'status',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###
