"""empty message

Revision ID: 4341fc44b8d3
Revises: 6291e7a62793
Create Date: 2018-12-07 10:17:31.796200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4341fc44b8d3'
down_revision = '6291e7a62793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('status', sa.SmallInteger(), nullable=True))
    op.add_column('gift', sa.Column('status', sa.SmallInteger(), nullable=True))
    op.add_column('menu', sa.Column('status', sa.SmallInteger(), nullable=True))
    op.add_column('submenu', sa.Column('status', sa.SmallInteger(), nullable=True))
    op.add_column('user', sa.Column('status', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    op.drop_column('submenu', 'status')
    op.drop_column('menu', 'status')
    op.drop_column('gift', 'status')
    op.drop_column('book', 'status')
    # ### end Alembic commands ###
