"""empty message

Revision ID: 47ad35af57cf
Revises: c70718a59826
Create Date: 2019-07-01 14:52:15.308000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47ad35af57cf'
down_revision = 'c70718a59826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('username', mysql.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
