"""empty message

Revision ID: 5b857f368fb0
Revises: 2d0c3c99ce38
Create Date: 2019-01-11 15:32:52.971000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b857f368fb0'
down_revision = '2d0c3c99ce38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenu', sa.Column('menu_id', sa.Integer(), nullable=True))
    op.drop_constraint('submenu_ibfk_1', 'submenu', type_='foreignkey')
    op.create_foreign_key(None, 'submenu', 'menu', ['menu_id'], ['id'])
    op.drop_column('submenu', 'mid')
    op.drop_column('submenu', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenu', sa.Column('path', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('submenu', sa.Column('mid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'submenu', type_='foreignkey')
    op.create_foreign_key('submenu_ibfk_1', 'submenu', 'menu', ['mid'], ['id'])
    op.drop_column('submenu', 'menu_id')
    # ### end Alembic commands ###
