"""empty message

Revision ID: 6291e7a62793
Revises: 
Create Date: 2018-12-07 10:14:29.342200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6291e7a62793'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'status')
    op.drop_column('gift', 'status')
    op.add_column('submenu', sa.Column('pic', sa.String(length=50), nullable=False))
    op.drop_column('user', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.drop_column('submenu', 'pic')
    op.add_column('gift', sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('book', sa.Column('status', mysql.SMALLINT(display_width=6), server_default=sa.text("'1'"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
