"""empty message

Revision ID: 8c5c76d10f12
Revises: 38c231ae8462
Create Date: 2019-07-01 10:11:45.886600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5c76d10f12'
down_revision = '38c231ae8462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'user_id')
    # ### end Alembic commands ###
