"""empty message

Revision ID: ab1c33d2dce1
Revises: 717a78a53cc0
Create Date: 2018-12-16 11:41:59.995793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1c33d2dce1'
down_revision = '717a78a53cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenu', sa.Column('menu_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submenu', 'menu_name')
    # ### end Alembic commands ###
