"""empty message

Revision ID: c70718a59826
Revises: 8c5c76d10f12
Create Date: 2019-07-01 14:30:09.988000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70718a59826'
down_revision = '8c5c76d10f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('username', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'username')
    # ### end Alembic commands ###
