"""empty message

Revision ID: d9f586e1eb5d
Revises: e8d9d1a011cf
Create Date: 2019-01-14 11:43:22.721400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f586e1eb5d'
down_revision = 'e8d9d1a011cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('en_name', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'en_name')
    # ### end Alembic commands ###
