"""empty message

Revision ID: e8d9d1a011cf
Revises: 5b857f368fb0
Create Date: 2019-01-11 15:48:03.118000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d9d1a011cf'
down_revision = '5b857f368fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenu', sa.Column('path', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submenu', 'path')
    # ### end Alembic commands ###
